# SPDX-License-Identifier: Apache-2.0

import os
import pathlib
import sys

import tomllib
from setuptools import setup


def _package_version() -> str:
    project = tomllib.loads(pathlib.Path("pyproject.toml").read_text())
    return project["tool"]["vllm_exl3_plugin"]["base_version"]


def _should_build_extension() -> bool:
    packaging_commands = {"sdist", "egg_info", "dist_info"}
    if any(command in packaging_commands for command in sys.argv[1:]):
        return False
    # Opt-in: without it the package is pure Python (config, loader, routing and
    # the CPU tests work; the linear method needs the ops at runtime).
    return os.environ.get("VLLM_EXL3_BUILD") == "1"


setup_kwargs: dict = {"version": _package_version()}

if _should_build_extension():
    from torch.utils.cpp_extension import BuildExtension, CUDAExtension

    # exllamav3 d3739fd (csrc/exl3, vendored unmodified, see csrc/exl3/VENDORED.md):
    # every .cu of the dense-linear closure, plus csrc/exl3_shim.cu (all adaptation).
    # Same nvcc flags as exllamav3's util/cuda_flags.py (minus --compress-mode).
    csrc = pathlib.Path("vllm_exl3_plugin/csrc")
    vendored = sorted(str(p) for p in (csrc / "exl3").rglob("*.cu"))
    sources = [str(csrc / "exl3_shim.cu"), *vendored]
    nvcc_args = [
        "-O3",
        "--use_fast_math",
        "-Xcudafe", "--diag_suppress=177",
        "-Xcudafe", "--diag_suppress=20012",
    ]
    cxx_args = ["-O3"]
    wheel_inc: list[str] = []
    # cublas_v2.h / cusparse.h (vendored hgemm, torch's CUDAContextLight.h): a pip-only
    # toolkit (tools/setup-cuda-toolchain.sh) lacks them, so fall back to the nvidia wheels'
    # headers, as plugin/setup.py does. The symbols resolve through libtorch_cuda's cuBLAS.
    try:
        import nvidia

        for base in nvidia.__path__:
            for inc in sorted(pathlib.Path(base).glob("*/include")):
                if (inc / "cublas_v2.h").exists():
                    wheel_inc += ["-Xcompiler", f"-idirafter,{inc}"]
                    cxx_args += ["-idirafter", str(inc)]
    except ImportError:
        pass
    nvcc_args += wheel_inc
    # trellis-serve 1ace59c (csrc/trellis_serve, vendored unmodified, see its VENDORED.md):
    # the multi-row kernel as a second extension, so _C_exl3 stays the phase-1 library.
    # exl3_marlin.cu + csrc/exl3_mr_shim.cu + one instantiation unit per (row family, codebook,
    # K), generated as upstream's cuda/csrc/setup.py does; upstream's nvcc flags and defaults.
    # VLLM_EXL3_MR_BUILD=0 skips it.
    ts = csrc / "trellis_serve"
    gen = pathlib.Path("build/trellis_gen").resolve()
    gen.mkdir(parents=True, exist_ok=True)
    variants = [(mb, 2, kb) for mb in range(5) for kb in (3, 4, 5)]  # mb 0 = rows <= 8; cb 2 = mul1

    def _write(path: pathlib.Path, text: str) -> None:
        if not path.exists() or path.read_text() != text:  # keep ninja's timestamps
            path.write_text(text)

    # The kernels compile from exl3_marlin_template_h16.h: the vendored template with the owned patch
    # csrc/exl3_marlin_h16.patch (fp16-accumulate MMA folded into fp32 per k-stage), generated here so the
    # vendored file stays byte-identical. The instance units are upstream's exl3_marlin_inst.h with that
    # template in place of exl3_marlin_template.h.
    import subprocess

    h16 = gen / "exl3_marlin_template_h16.h"
    patched = subprocess.run(["patch", "-s", "-o", "-", str(ts / "exl3_marlin_template.h"),
                              str(csrc / "exl3_marlin_h16.patch")], check=True, capture_output=True, text=True).stdout
    _write(h16, patched)
    mr_sources = [str(ts / "exl3_marlin.cu"), str(csrc / "exl3_mr_shim.cu")]
    for mb, cb, kb in variants:
        unit = gen / f"inst_mb{mb}_cb{cb}_k{kb}.cu"
        _write(unit, f"#define TRELLIS_INST_MB {mb}\n#define TRELLIS_INST_CB {cb}\n#define TRELLIS_INST_KB {kb}\n"
                     "#define MARLIN_NAMESPACE_NAME trellis_exl3_marlin\n#define TRELLIS_KERNEL_DEFINED\n"
                     "#include \"exl3_marlin_template_h16.h\"\n#include \"exl3_marlin_kernels.h\"\n"
                     "namespace MARLIN_NAMESPACE_NAME {\n"
                     "#define TRELLIS_INST(threads, tn, tk, mb, cb, kb) \\\n"
                     "  template __global__ void TRELLIS_KERNEL(threads, tn, tk, mb, cb, kb)(TRELLIS_KERNEL_PARAMS);\n"
                     "TRELLIS_THREAD_CFGS(TRELLIS_INST, TRELLIS_INST_MB, TRELLIS_INST_CB, TRELLIS_INST_KB)\n}\n")
        mr_sources.append(str(unit))
    _write(gen / "trellis_families.h",
           "// generated by plugin-exl3/setup.py\n#pragma once\n#define TRELLIS_VARIANTS(X) "
           + " ".join(f"X({mb}, {cb}, {kb})" for mb, cb, kb in variants) + "\n")
    mr_nvcc = ["-O3", "--use_fast_math", "-static-global-template-stub=false",
               "-DTRELLIS_WRAP_LOAD=1", "-DTRELLIS_PROBES=0", "-DTRELLIS_SLOT_REDUCE=1",
               "-DTRELLIS_MOE_MINBLOCKS_M8=2", "-DTRELLIS_MCG_SELFADD=1",
               # upstream's experiment knob (0 | 3 | 6 of the K3 window shifts on the FMA pipe), bit-exact
               "-DTRELLIS_K3_IMAD_SHIFTS=" + os.environ.get("TRELLIS_K3_IMAD_SHIFTS", "0")]
    mr_nvcc += wheel_inc
    ext_modules = [
        CUDAExtension(
            name="vllm_exl3_plugin._C_exl3",
            sources=sources,
            # Absolute: torch's ninja build runs from build/temp*.
            include_dirs=[str((csrc / "exl3").resolve()), str(csrc.resolve())],
            extra_compile_args={"cxx": cxx_args, "nvcc": nvcc_args},
        )
    ]
    if os.environ.get("VLLM_EXL3_MR_BUILD", "1") == "1":
        ext_modules.append(
            CUDAExtension(
                name="vllm_exl3_plugin._C_exl3_mr",
                sources=mr_sources,
                include_dirs=[str(ts.resolve()), str((ts / "third_party/marlin").resolve()), str(gen)],
                extra_compile_args={"cxx": cxx_args, "nvcc": mr_nvcc},
            )
        )
    setup_kwargs.update(ext_modules=ext_modules, cmdclass={"build_ext": BuildExtension})

setup(**setup_kwargs)
